# Generated by Django 6.0.6 on 2026-06-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_brand_description_alter_brand_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Perfil de cliente', 'verbose_name_plural': 'Perfiles de clientes'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'verbose_name': 'Detalle de factura', 'verbose_name_plural': 'Detalles de factura'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'verbose_name': 'Grupo de producto', 'verbose_name_plural': 'Grupos de productos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='billing.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='payment_terms',
            field=models.CharField(choices=[('cash', 'Contado'), ('credit_15', '15 días'), ('credit_30', '30 días'), ('credit_60', '60 días')], default='cash', max_length=15, verbose_name='Condiciones de pago'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='taxpayer_type',
            field=models.CharField(choices=[('final', 'Consumidor final'), ('ruc', 'RUC'), ('rise', 'RISE')], default='final', max_length=10, verbose_name='Tipo de contribuyente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de factura'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='billing.invoice', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_details', to='billing.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='billing.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='billing.productgroup', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='billing.supplier', verbose_name='Proveedores'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de grupo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de empresa'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
